export const budgetDefaultEntries = [
  { id: 'cat-1-1', label: 'Salaire', value: 1200, cat: 'cat-1' },
  { id: 'cat-1-2', label: 'CAF', value: 240, cat: 'cat-1' },
  { id: 'cat-2-1', label: 'Loyer', value: 540, cat: 'cat-2' },
  { id: 'cat-2-2', label: 'Eau', value: 30, cat: 'cat-2' },
  { id: 'cat-3-1', label: 'Mutuelle', value: 40, cat: 'cat-3' },
  { id: 'cat-4-1', label: 'Assurance voiture', value: 70, cat: 'cat-4' },
  { id: 'cat-4-2', label: 'Abonnement Train/Bus', value: 30, cat: 'cat-4' },
  { id: 'cat-5-1', label: 'Taxe habitation', value: 20, cat: 'cat-5' },
  { id: 'cat-5-2', label: 'Impôts revenue', value: 30, cat: 'cat-5' },
  { id: 'cat-6-1', label: 'Cantine', value: 50, cat: 'cat-6' },
  { id: 'cat-7-1', label: 'Téléphone', value: 20, cat: 'cat-7' },
  { id: 'cat-7-2', label: 'Internet/TV', value: 30, cat: 'cat-7' },
  { id: 'cat-8-1', label: 'Super U 01/02', value: 80, cat: 'cat-8' },
  { id: 'cat-8-2', label: 'Bio Coop 03/02', value: 50, cat: 'cat-8' },
  { id: 'cat-8-3', label: 'Leader 10/02', value: 120, cat: 'cat-8' },
  { id: 'cat-8-4', label: 'Super U 16/02', value: 90, cat: 'cat-8' },
  { id: 'cat-8-5', label: 'Bio Coop 22/02', value: 40, cat: 'cat-8' },
  { id: 'cat-8-6', label: 'MacDo 23/02', value: 30, cat: 'cat-8' },
  { id: 'cat-9-1', label: 'Vêtement Zara', value: 90, cat: 'cat-9' },
  { id: 'cat-9-2', label: 'Tabac', value: 24, cat: 'cat-9' },
];
export const budgetDefaultGroups = [
  {
    id: 'group-1',
    label: 'Logement',
    labelId: 'housing',
    data: ['cat-2-1', 'cat-2-2'],
  },
  {
    id: 'group-2',
    label: 'Santé',
    labelId: 'health',
    data: ['cat-3-1'],
  },
  {
    id: 'group-3',
    label: 'Transport',
    labelId: 'transport',
    data: ['cat-4-1', 'cat-4-2'],
  },
  {
    id: 'group-4',
    label: 'Impôts',
    labelId: 'taxes',
    data: ['cat-5-1', 'cat-5-2'],
  },
  {
    id: 'group-5',
    label: 'Enfants',
    labelId: 'children',
    data: ['cat-6-1'],
  },
  {
    id: 'group-6',
    label: 'Communication',
    labelId: 'comm',
    data: ['cat-7-1', 'cat-7-2'],
  },
];
export const budgetDefaultCatergories = [
  {
    id: 'cat-1',
    label: 'Revenues',
    labelId: 'income',
    color: 'green',
    data: ['cat-1-1', 'cat-1-2'],
  },
  {
    id: 'cat-2',
    label: 'Dépenses fixes',
    labelId: 'expense',
    color: 'blue',
    group: ['group-1', 'group-2', 'group-3', 'group-4', 'group-5', 'group-6'],
  },
  {
    id: 'cat-3',
    label: 'Alimentation',
    labelId: 'food',
    color: 'yellow',
    data: ['cat-8-1', 'cat-8-2', 'cat-8-3', 'cat-8-4', 'cat-8-5', 'cat-8-6'],
  },
  {
    id: 'cat-4',
    label: 'Loisir / Divers',
    labelId: 'leasure',
    color: 'orange',
    data: ['cat-9-1', 'cat-9-2'],
  },
];
